# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maktab.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(786, 580)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 127);\n"
"background-color:rgb(255, 255, 127)")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setStyleSheet("background-color:rgb(170, 255, 127)")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    ;\n"
"font: ;\n"
"background-color: rgb(255, 170, 0); ;\n"
"color: rgb(170, 170, 0);\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_53 = QtWidgets.QPushButton(Form)
        self.pushButton_53.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color:rgb(85, 255, 127) ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_53.setObjectName("pushButton_53")
        self.gridLayout_2.addWidget(self.pushButton_53, 13, 3, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(Form)
        self.pushButton_24.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color:rgb(85, 255, 127) ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_2.addWidget(self.pushButton_24, 13, 0, 1, 1)
        self.pushButton_35 = QtWidgets.QPushButton(Form)
        self.pushButton_35.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_35.setObjectName("pushButton_35")
        self.gridLayout_2.addWidget(self.pushButton_35, 10, 1, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(Form)
        self.pushButton_27.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: rgb(170, 170, 0) ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout_2.addWidget(self.pushButton_27, 1, 4, 1, 1)
        self.pushButton_39 = QtWidgets.QPushButton(Form)
        self.pushButton_39.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_39.setObjectName("pushButton_39")
        self.gridLayout_2.addWidget(self.pushButton_39, 6, 2, 1, 1)
        self.pushButton_34 = QtWidgets.QPushButton(Form)
        self.pushButton_34.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_34.setObjectName("pushButton_34")
        self.gridLayout_2.addWidget(self.pushButton_34, 9, 1, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(Form)
        self.pushButton_21.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_2.addWidget(self.pushButton_21, 8, 0, 1, 1)
        self.pushButton_43 = QtWidgets.QPushButton(Form)
        self.pushButton_43.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_43.setObjectName("pushButton_43")
        self.gridLayout_2.addWidget(self.pushButton_43, 10, 2, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(Form)
        self.pushButton_25.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_2.addWidget(self.pushButton_25, 3, 2, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_37 = QtWidgets.QPushButton(Form)
        self.pushButton_37.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_37.setObjectName("pushButton_37")
        self.horizontalLayout_15.addWidget(self.pushButton_37)
        self.gridLayout_2.addLayout(self.horizontalLayout_15, 4, 2, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(Form)
        self.pushButton_30.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout_2.addWidget(self.pushButton_30, 5, 1, 1, 1)
        self.pushButton_41 = QtWidgets.QPushButton(Form)
        self.pushButton_41.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_41.setObjectName("pushButton_41")
        self.gridLayout_2.addWidget(self.pushButton_41, 8, 2, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_2.addWidget(self.pushButton_12, 2, 3, 1, 1)
        self.pushButton_52 = QtWidgets.QPushButton(Form)
        self.pushButton_52.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_52.setObjectName("pushButton_52")
        self.gridLayout_2.addWidget(self.pushButton_52, 10, 3, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(Form)
        self.pushButton_20.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_2.addWidget(self.pushButton_20, 7, 0, 1, 1)
        self.pushButton_38 = QtWidgets.QPushButton(Form)
        self.pushButton_38.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_38.setObjectName("pushButton_38")
        self.gridLayout_2.addWidget(self.pushButton_38, 5, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(Form)
        self.pushButton_28.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout_2.addWidget(self.pushButton_28, 3, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 0, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(Form)
        self.pushButton_18.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_2.addWidget(self.pushButton_18, 5, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_2.addWidget(self.pushButton_10, 2, 0, 1, 1)
        self.pushButton_49 = QtWidgets.QPushButton(Form)
        self.pushButton_49.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_49.setObjectName("pushButton_49")
        self.gridLayout_2.addWidget(self.pushButton_49, 7, 3, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(Form)
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_2.addWidget(self.pushButton_13, 0, 1, 1, 1)
        self.pushButton_31 = QtWidgets.QPushButton(Form)
        self.pushButton_31.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout_2.addWidget(self.pushButton_31, 6, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(Form)
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_2.addWidget(self.pushButton_14, 1, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 3, 1, 1)
        self.pushButton_47 = QtWidgets.QPushButton(Form)
        self.pushButton_47.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_47.setObjectName("pushButton_47")
        self.gridLayout_2.addWidget(self.pushButton_47, 5, 3, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(Form)
        self.pushButton_26.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: rgb(170, 170, 0) ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout_2.addWidget(self.pushButton_26, 0, 4, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(Form)
        self.pushButton_17.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_2.addWidget(self.pushButton_17, 4, 0, 1, 1)
        self.pushButton_33 = QtWidgets.QPushButton(Form)
        self.pushButton_33.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_33.setObjectName("pushButton_33")
        self.gridLayout_2.addWidget(self.pushButton_33, 8, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 1, 3, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 1, 2, 1, 1)
        self.pushButton_50 = QtWidgets.QPushButton(Form)
        self.pushButton_50.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_50.setObjectName("pushButton_50")
        self.gridLayout_2.addWidget(self.pushButton_50, 8, 3, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_2.addWidget(self.pushButton_9, 1, 0, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(Form)
        self.pushButton_32.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout_2.addWidget(self.pushButton_32, 7, 1, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(Form)
        self.pushButton_23.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_2.addWidget(self.pushButton_23, 10, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_2.addWidget(self.pushButton_11, 2, 2, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(Form)
        self.pushButton_19.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_2.addWidget(self.pushButton_19, 6, 0, 1, 1)
        self.pushButton_42 = QtWidgets.QPushButton(Form)
        self.pushButton_42.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_42.setObjectName("pushButton_42")
        self.gridLayout_2.addWidget(self.pushButton_42, 9, 2, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(Form)
        self.pushButton_22.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_2.addWidget(self.pushButton_22, 9, 0, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(Form)
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_2.addWidget(self.pushButton_16, 3, 0, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(Form)
        self.pushButton_29.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout_2.addWidget(self.pushButton_29, 4, 1, 1, 1)
        self.pushButton_54 = QtWidgets.QPushButton(Form)
        self.pushButton_54.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: rgb(170, 170, 0) ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_54.setObjectName("pushButton_54")
        self.gridLayout_2.addWidget(self.pushButton_54, 2, 4, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_46 = QtWidgets.QPushButton(Form)
        self.pushButton_46.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_46.setObjectName("pushButton_46")
        self.horizontalLayout_14.addWidget(self.pushButton_46)
        self.gridLayout_2.addLayout(self.horizontalLayout_14, 4, 3, 1, 1)
        self.pushButton_51 = QtWidgets.QPushButton(Form)
        self.pushButton_51.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_51.setObjectName("pushButton_51")
        self.gridLayout_2.addWidget(self.pushButton_51, 9, 3, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(Form)
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_2.addWidget(self.pushButton_15, 2, 1, 1, 1)
        self.pushButton_48 = QtWidgets.QPushButton(Form)
        self.pushButton_48.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_48.setObjectName("pushButton_48")
        self.gridLayout_2.addWidget(self.pushButton_48, 6, 3, 1, 1)
        self.pushButton_36 = QtWidgets.QPushButton(Form)
        self.pushButton_36.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color:rgb(85, 255, 127) ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_36.setObjectName("pushButton_36")
        self.gridLayout_2.addWidget(self.pushButton_36, 13, 1, 1, 1)
        self.pushButton_45 = QtWidgets.QPushButton(Form)
        self.pushButton_45.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_45.setObjectName("pushButton_45")
        self.gridLayout_2.addWidget(self.pushButton_45, 3, 3, 1, 1)
        self.pushButton_40 = QtWidgets.QPushButton(Form)
        self.pushButton_40.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: #B34EE9 ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_40.setObjectName("pushButton_40")
        self.gridLayout_2.addWidget(self.pushButton_40, 7, 2, 1, 1)
        self.pushButton_44 = QtWidgets.QPushButton(Form)
        self.pushButton_44.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color:rgb(85, 255, 127) ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_44.setObjectName("pushButton_44")
        self.gridLayout_2.addWidget(self.pushButton_44, 13, 2, 1, 1)
        self.pushButton_55 = QtWidgets.QPushButton(Form)
        self.pushButton_55.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: rgb(170, 170, 0) ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_55.setObjectName("pushButton_55")
        self.gridLayout_2.addWidget(self.pushButton_55, 3, 4, 1, 1)
        self.pushButton_56 = QtWidgets.QPushButton(Form)
        self.pushButton_56.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: rgb(170, 170, 0) ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_56.setObjectName("pushButton_56")
        self.gridLayout_2.addWidget(self.pushButton_56, 4, 4, 1, 1)
        self.pushButton_57 = QtWidgets.QPushButton(Form)
        self.pushButton_57.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: rgb(170, 170, 0) ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_57.setObjectName("pushButton_57")
        self.gridLayout_2.addWidget(self.pushButton_57, 5, 4, 1, 1)
        self.pushButton_58 = QtWidgets.QPushButton(Form)
        self.pushButton_58.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: rgb(170, 170, 0) ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_58.setObjectName("pushButton_58")
        self.gridLayout_2.addWidget(self.pushButton_58, 6, 4, 1, 1)
        self.pushButton_59 = QtWidgets.QPushButton(Form)
        self.pushButton_59.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: rgb(170, 170, 0) ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_59.setObjectName("pushButton_59")
        self.gridLayout_2.addWidget(self.pushButton_59, 7, 4, 1, 1)
        self.pushButton_60 = QtWidgets.QPushButton(Form)
        self.pushButton_60.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: rgb(170, 170, 0) ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_60.setObjectName("pushButton_60")
        self.gridLayout_2.addWidget(self.pushButton_60, 8, 4, 1, 1)
        self.pushButton_61 = QtWidgets.QPushButton(Form)
        self.pushButton_61.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: rgb(170, 170, 0) ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_61.setObjectName("pushButton_61")
        self.gridLayout_2.addWidget(self.pushButton_61, 9, 4, 1, 1)
        self.pushButton_62 = QtWidgets.QPushButton(Form)
        self.pushButton_62.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color: rgb(170, 170, 0) ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_62.setObjectName("pushButton_62")
        self.gridLayout_2.addWidget(self.pushButton_62, 10, 4, 1, 1)
        self.pushButton_63 = QtWidgets.QPushButton(Form)
        self.pushButton_63.setStyleSheet("QPushButton{\n"
"font: ;\n"
"background-color:rgb(85, 255, 127) ;\n"
"color: #080A12;\n"
"}\n"
"QPushButton:hover{\n"
"font: ;\n"
"background-color: red;\n"
"\n"
"}")
        self.pushButton_63.setObjectName("pushButton_63")
        self.gridLayout_2.addWidget(self.pushButton_63, 13, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "O\'zbekiston Respublikasi Toshkent shaxri Chilonzor tumani N-sonli  maktab"))
        self.pushButton.setText(_translate("Form", "Umumiy ma\'lumot"))
        self.pushButton_53.setText(_translate("Form", "Assistant"))
        self.pushButton_24.setText(_translate("Form", "Ustozlar"))
        self.pushButton_35.setText(_translate("Form", "11 B sinf"))
        self.pushButton_27.setText(_translate("Form", "2 sinf dars jadvali"))
        self.pushButton_39.setText(_translate("Form", "7 А класс"))
        self.pushButton_34.setText(_translate("Form", "10 B sinf"))
        self.pushButton_21.setText(_translate("Form", "9 A sinf"))
        self.pushButton_43.setText(_translate("Form", "11 А класс"))
        self.pushButton_25.setText(_translate("Form", "4 А класс"))
        self.pushButton_37.setText(_translate("Form", "5 А класс"))
        self.pushButton_30.setText(_translate("Form", "6 B sinf"))
        self.pushButton_41.setText(_translate("Form", "9 А класс"))
        self.pushButton_12.setText(_translate("Form", "3 В класс"))
        self.pushButton_52.setText(_translate("Form", "11 В класс"))
        self.pushButton_20.setText(_translate("Form", "8 A sinf"))
        self.pushButton_38.setText(_translate("Form", "6 А класс"))
        self.pushButton_3.setText(_translate("Form", "1 A класс"))
        self.pushButton_28.setText(_translate("Form", "4 B sinf"))
        self.pushButton_8.setText(_translate("Form", "1 A sinf"))
        self.pushButton_18.setText(_translate("Form", "6 A sinf"))
        self.pushButton_10.setText(_translate("Form", "3 A sinf"))
        self.pushButton_49.setText(_translate("Form", "8 В класс"))
        self.pushButton_13.setText(_translate("Form", "1  B sinf"))
        self.pushButton_31.setText(_translate("Form", "7 B sinf"))
        self.pushButton_14.setText(_translate("Form", "2 B sinf"))
        self.pushButton_2.setText(_translate("Form", "1 В класс"))
        self.pushButton_47.setText(_translate("Form", "6 В класс"))
        self.pushButton_26.setText(_translate("Form", "1 sinf dars jadvali"))
        self.pushButton_17.setText(_translate("Form", "5 A sinf"))
        self.pushButton_33.setText(_translate("Form", "9 B sinf"))
        self.pushButton_5.setText(_translate("Form", "2 В класс"))
        self.pushButton_4.setText(_translate("Form", "2 А класс"))
        self.pushButton_50.setText(_translate("Form", "9 В класс"))
        self.pushButton_9.setText(_translate("Form", "2 A sinf"))
        self.pushButton_32.setText(_translate("Form", "8 B sinf"))
        self.pushButton_23.setText(_translate("Form", "11 A sinf"))
        self.pushButton_11.setText(_translate("Form", "3 А класс"))
        self.pushButton_19.setText(_translate("Form", "7 A sinf"))
        self.pushButton_42.setText(_translate("Form", "10 А класс"))
        self.pushButton_22.setText(_translate("Form", "10 A sinf"))
        self.pushButton_16.setText(_translate("Form", "4 A sinf"))
        self.pushButton_29.setText(_translate("Form", "5 B sinf"))
        self.pushButton_54.setText(_translate("Form", "3 sinf dars jadvali"))
        self.pushButton_46.setText(_translate("Form", "5 В класс"))
        self.pushButton_51.setText(_translate("Form", "10 В класс"))
        self.pushButton_15.setText(_translate("Form", "3 B sinf"))
        self.pushButton_48.setText(_translate("Form", "7 В класс"))
        self.pushButton_36.setText(_translate("Form", "Rahbariyat"))
        self.pushButton_45.setText(_translate("Form", "4 В класс"))
        self.pushButton_40.setText(_translate("Form", "8 А класс"))
        self.pushButton_44.setText(_translate("Form", "Hizmatlar"))
        self.pushButton_55.setText(_translate("Form", "4 sinf dars jadvali"))
        self.pushButton_56.setText(_translate("Form", "5 sinf dars jadvali"))
        self.pushButton_57.setText(_translate("Form", "6 sinf dars jadvali"))
        self.pushButton_58.setText(_translate("Form", "7 sinf dars jadvali"))
        self.pushButton_59.setText(_translate("Form", "8 sinf dars jadvali"))
        self.pushButton_60.setText(_translate("Form", "9 sinf dars jadvali"))
        self.pushButton_61.setText(_translate("Form", "10 sinf dars jadvali"))
        self.pushButton_62.setText(_translate("Form", "11 sinf dars jadvali"))
        self.pushButton_63.setText(_translate("Form", "Aniq vaqt"))


